GET http://localhost:3002/api/v1/posts

###
POST http://localhost:3002/api/v1/posts
Content-Type: application/json

{
    "caracteristicas": {
        "edad": "2 años",
        "color": "blanco",
        "sexo": "M",
        "tamaño": "XL"
    },
    "ubicacion": {
        "referencia": "Plaza Mayor de Nuevo Chimbote",
        "lat": -9.122916490721595,
        "lng": -78.53084177327464
    },
    "titulo": "Perro labrador perdido",
    "tipo": "perro",
    "etiquetas": [
        "perro",
        "labrador",
        "ayuda"
    ],
    "descripcion": "quidem molestiae nostrum voluptas velit error similique debitis et nihil hic et at provident aut quo facilis et quae ullam sint velit et rerum non ipsa iure cupiditate adipisci earum reprehenderit aspernatur veri",
    "foto_principal": 0,
    "fotos": [
        "https://images.dog.ceo/breeds/bluetick/n02088632_2870.jpg"
    ]
}

###
POST http://localhost:3002/api/v1/posts
Content-Type: application/json

{
        "caracteristicas": {
            "edad": "6 meses",
            "color": "marron",
            "sexo": "M",
            "tamaño": "XS"
        },
        "ubicacion": {
            "referencia": "Mercado Buenos Aires",
            "lat": -9.127000168554577,
            "lng": -78.52001851957706
        },
        "titulo": "Gatito perdido",
        "tipo": "gato",
        "etiquetas": [
            "gato",
            "bebe",
            "ayuda"
        ],
        "descripcion": "voluptatem sed natus perspiciatis qui enim aut ut ipsum repellat occaecati eveniet aliquam accusamus ipsum delectus corrupti veniam inventore tenetur est totam voluptas culpa nihil eius et dolore molestiae laborum quis quos ut eos dolorem occaecati alias sed voluptates hic delectus velit consequatur",
        "foto_principal": 0,
        "fotos": [
            "https://images.dog.ceo/breeds/basenji/n02110806_6035.jpg"
        ]
}
